# The package name
name: com.hellopackage.hellotestpackage
# The package display name
displayName: Hello Test Package
# The short package description
description: An unity package example
# The repository url
repoUrl: 'https://github.com/utkarsh5e/HelloTestPackage.git'
# The forked repository url
parentRepoUrl: null
# The Software Package Data Exchange® (SPDX®) license id
licenseSpdxId: MIT
# The license name
licenseName: MIT License
# A list of topic slugs
topics:
  - utilities
# Filtering Git tags based on their prefix. It’s particularly useful for monorepos to distinguish between Git tags. i.e. 'com.example.foo/'.
gitTagPrefix: ''
# The regular expression that specifies intentionally untracked Git tags that should be ignored
gitTagIgnore: '-master$'
# The minimal version to build. Leave it blank to build all versions.
minVersion: '1.1.0'
# The README.md file path (branchname:filename)
readme: 'master:README.md'
# The package hunter's GitHub username
hunter: author